### PR TITLE
feat(console) add a simple job queue

### PR DESCRIPTION
**Pull request by sidux**
This PR adds a job queue (in a simple file) and takes into account user session. The queue file is created under app/logs and is deleted automatically when the queue is empty.

There is a second file that containers the current command dump, used to send the current command output to the client (ajax request with an interval).

It needs running a command (`oc:console:execute:commands`) in the server as a job (option `-l`) or adding it to the cron table (executing every sec)

### CODE REVIEW

**Comment by eXorus** [comment]
@sidux I don't understand.
What is the goal?

**Comment by sidux** [comment]
@eXorus Commands don't work on stage (/_console) because fpm or nginx have both ttl's which kills php even if it has no timeout, so i made the call to the command async by creating a queue taking commands that should be executed and an ajax checking for command status to update the view.
This makes long running commands possible, for example oc:redis:flush should work now

**Comment by eXorus** [comment]
Did you test it on stage? Does it work?

If yes great work because the console was useless right now.

**Comment by sidux** [comment]
@eXorus I tested only in local, to be able to test in stage, I need to add the command launcher to a crontab, for that I asked morea to make crontab configurable by a file on the projet, Im waiting for the ticket to be done.

**Review by fredericjaume-oc — APPROVED** [review]
Nice!

**Review by kletord — APPROVED** [review]

**Pull request closed without merging**
